FROM golang:alpine AS builder
WORKDIR /app
COPY go.mod go.sum ./
RUN go mod download
COPY . .
RUN CGO_ENABLED=0 GOOS=linux go build -o /grpc-server ./cmd/server

FROM alpine:latest
WORKDIR /app
COPY --from=builder /grpc-server ./grpc-server
CMD ["./grpc-server"]
