// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type CreateOrderInput struct {
	UserID      string `json:"userId"`
	ProductName string `json:"productName"`
	Quantity    int    `json:"quantity"`
}

type CreateUserInput struct {
	Name  string `json:"name"`
	Email string `json:"email"`
}

type Mutation struct {
}

type Order struct {
	ID          string `json:"id"`
	UserID      string `json:"userId"`
	ProductName string `json:"productName"`
	Quantity    int    `json:"quantity"`
	Status      string `json:"status"`
}

type OrderTracking struct {
	ID       string `json:"id"`
	OrderID  string `json:"orderId"`
	Status   string `json:"status"`
	Location string `json:"location"`
}

type Query struct {
}

type UpdateOrderInput struct {
	ProductName *string `json:"productName,omitempty"`
	Quantity    *int    `json:"quantity,omitempty"`
	Status      *string `json:"status,omitempty"`
}

type UpdateTrackingInput struct {
	OrderID  string `json:"orderId"`
	Status   string `json:"status"`
	Location string `json:"location"`
}

type UpdateUserInput struct {
	Name  *string `json:"name,omitempty"`
	Email *string `json:"email,omitempty"`
}

type User struct {
	ID    string `json:"id"`
	Name  string `json:"name"`
	Email string `json:"email"`
}
