// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.0
// source: internal/proto/tracking.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type OrderTracking struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	OrderId       string                 `protobuf:"bytes,2,opt,name=order_id,json=orderId,proto3" json:"order_id,omitempty"`
	Status        string                 `protobuf:"bytes,3,opt,name=status,proto3" json:"status,omitempty"`
	Location      string                 `protobuf:"bytes,4,opt,name=location,proto3" json:"location,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OrderTracking) Reset() {
	*x = OrderTracking{}
	mi := &file_internal_proto_tracking_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OrderTracking) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OrderTracking) ProtoMessage() {}

func (x *OrderTracking) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_tracking_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OrderTracking.ProtoReflect.Descriptor instead.
func (*OrderTracking) Descriptor() ([]byte, []int) {
	return file_internal_proto_tracking_proto_rawDescGZIP(), []int{0}
}

func (x *OrderTracking) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *OrderTracking) GetOrderId() string {
	if x != nil {
		return x.OrderId
	}
	return ""
}

func (x *OrderTracking) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *OrderTracking) GetLocation() string {
	if x != nil {
		return x.Location
	}
	return ""
}

type UpdateTrackingRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OrderId       string                 `protobuf:"bytes,1,opt,name=order_id,json=orderId,proto3" json:"order_id,omitempty"`
	Status        string                 `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`
	Location      string                 `protobuf:"bytes,3,opt,name=location,proto3" json:"location,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateTrackingRequest) Reset() {
	*x = UpdateTrackingRequest{}
	mi := &file_internal_proto_tracking_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateTrackingRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateTrackingRequest) ProtoMessage() {}

func (x *UpdateTrackingRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_tracking_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateTrackingRequest.ProtoReflect.Descriptor instead.
func (*UpdateTrackingRequest) Descriptor() ([]byte, []int) {
	return file_internal_proto_tracking_proto_rawDescGZIP(), []int{1}
}

func (x *UpdateTrackingRequest) GetOrderId() string {
	if x != nil {
		return x.OrderId
	}
	return ""
}

func (x *UpdateTrackingRequest) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *UpdateTrackingRequest) GetLocation() string {
	if x != nil {
		return x.Location
	}
	return ""
}

type UpdateTrackingResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Tracking      *OrderTracking         `protobuf:"bytes,1,opt,name=tracking,proto3" json:"tracking,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateTrackingResponse) Reset() {
	*x = UpdateTrackingResponse{}
	mi := &file_internal_proto_tracking_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateTrackingResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateTrackingResponse) ProtoMessage() {}

func (x *UpdateTrackingResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_tracking_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateTrackingResponse.ProtoReflect.Descriptor instead.
func (*UpdateTrackingResponse) Descriptor() ([]byte, []int) {
	return file_internal_proto_tracking_proto_rawDescGZIP(), []int{2}
}

func (x *UpdateTrackingResponse) GetTracking() *OrderTracking {
	if x != nil {
		return x.Tracking
	}
	return nil
}

type TrackOrderRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OrderId       string                 `protobuf:"bytes,1,opt,name=order_id,json=orderId,proto3" json:"order_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TrackOrderRequest) Reset() {
	*x = TrackOrderRequest{}
	mi := &file_internal_proto_tracking_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TrackOrderRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TrackOrderRequest) ProtoMessage() {}

func (x *TrackOrderRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_tracking_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TrackOrderRequest.ProtoReflect.Descriptor instead.
func (*TrackOrderRequest) Descriptor() ([]byte, []int) {
	return file_internal_proto_tracking_proto_rawDescGZIP(), []int{3}
}

func (x *TrackOrderRequest) GetOrderId() string {
	if x != nil {
		return x.OrderId
	}
	return ""
}

type TrackOrderResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Trackings     []*OrderTracking       `protobuf:"bytes,1,rep,name=trackings,proto3" json:"trackings,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TrackOrderResponse) Reset() {
	*x = TrackOrderResponse{}
	mi := &file_internal_proto_tracking_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TrackOrderResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TrackOrderResponse) ProtoMessage() {}

func (x *TrackOrderResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_tracking_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TrackOrderResponse.ProtoReflect.Descriptor instead.
func (*TrackOrderResponse) Descriptor() ([]byte, []int) {
	return file_internal_proto_tracking_proto_rawDescGZIP(), []int{4}
}

func (x *TrackOrderResponse) GetTrackings() []*OrderTracking {
	if x != nil {
		return x.Trackings
	}
	return nil
}

var File_internal_proto_tracking_proto protoreflect.FileDescriptor

const file_internal_proto_tracking_proto_rawDesc = "" +
	"\n" +
	"\x1dinternal/proto/tracking.proto\x12\btracking\"n\n" +
	"\rOrderTracking\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x19\n" +
	"\border_id\x18\x02 \x01(\tR\aorderId\x12\x16\n" +
	"\x06status\x18\x03 \x01(\tR\x06status\x12\x1a\n" +
	"\blocation\x18\x04 \x01(\tR\blocation\"f\n" +
	"\x15UpdateTrackingRequest\x12\x19\n" +
	"\border_id\x18\x01 \x01(\tR\aorderId\x12\x16\n" +
	"\x06status\x18\x02 \x01(\tR\x06status\x12\x1a\n" +
	"\blocation\x18\x03 \x01(\tR\blocation\"M\n" +
	"\x16UpdateTrackingResponse\x123\n" +
	"\btracking\x18\x01 \x01(\v2\x17.tracking.OrderTrackingR\btracking\".\n" +
	"\x11TrackOrderRequest\x12\x19\n" +
	"\border_id\x18\x01 \x01(\tR\aorderId\"K\n" +
	"\x12TrackOrderResponse\x125\n" +
	"\ttrackings\x18\x01 \x03(\v2\x17.tracking.OrderTrackingR\ttrackings2\xaf\x01\n" +
	"\x0fTrackingService\x12S\n" +
	"\x0eUpdateTracking\x12\x1f.tracking.UpdateTrackingRequest\x1a .tracking.UpdateTrackingResponse\x12G\n" +
	"\n" +
	"TrackOrder\x12\x1b.tracking.TrackOrderRequest\x1a\x1c.tracking.TrackOrderResponseB!Z\x1ftracking_service/internal/protob\x06proto3"

var (
	file_internal_proto_tracking_proto_rawDescOnce sync.Once
	file_internal_proto_tracking_proto_rawDescData []byte
)

func file_internal_proto_tracking_proto_rawDescGZIP() []byte {
	file_internal_proto_tracking_proto_rawDescOnce.Do(func() {
		file_internal_proto_tracking_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_internal_proto_tracking_proto_rawDesc), len(file_internal_proto_tracking_proto_rawDesc)))
	})
	return file_internal_proto_tracking_proto_rawDescData
}

var file_internal_proto_tracking_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_internal_proto_tracking_proto_goTypes = []any{
	(*OrderTracking)(nil),          // 0: tracking.OrderTracking
	(*UpdateTrackingRequest)(nil),  // 1: tracking.UpdateTrackingRequest
	(*UpdateTrackingResponse)(nil), // 2: tracking.UpdateTrackingResponse
	(*TrackOrderRequest)(nil),      // 3: tracking.TrackOrderRequest
	(*TrackOrderResponse)(nil),     // 4: tracking.TrackOrderResponse
}
var file_internal_proto_tracking_proto_depIdxs = []int32{
	0, // 0: tracking.UpdateTrackingResponse.tracking:type_name -> tracking.OrderTracking
	0, // 1: tracking.TrackOrderResponse.trackings:type_name -> tracking.OrderTracking
	1, // 2: tracking.TrackingService.UpdateTracking:input_type -> tracking.UpdateTrackingRequest
	3, // 3: tracking.TrackingService.TrackOrder:input_type -> tracking.TrackOrderRequest
	2, // 4: tracking.TrackingService.UpdateTracking:output_type -> tracking.UpdateTrackingResponse
	4, // 5: tracking.TrackingService.TrackOrder:output_type -> tracking.TrackOrderResponse
	4, // [4:6] is the sub-list for method output_type
	2, // [2:4] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_internal_proto_tracking_proto_init() }
func file_internal_proto_tracking_proto_init() {
	if File_internal_proto_tracking_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_internal_proto_tracking_proto_rawDesc), len(file_internal_proto_tracking_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_internal_proto_tracking_proto_goTypes,
		DependencyIndexes: file_internal_proto_tracking_proto_depIdxs,
		MessageInfos:      file_internal_proto_tracking_proto_msgTypes,
	}.Build()
	File_internal_proto_tracking_proto = out.File
	file_internal_proto_tracking_proto_goTypes = nil
	file_internal_proto_tracking_proto_depIdxs = nil
}
