package resolver

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.89

import (
	"api_gateway/internal/graph"
	"api_gateway/internal/graph/model"
	"api_gateway/internal/proto/orderpb"
	"api_gateway/internal/proto/trackingpb"
	"api_gateway/internal/proto/userpb"
	"context"
	"fmt"
	"log"
)

// CreateUser is the resolver for the createUser field.
func (r *mutationResolver) CreateUser(ctx context.Context, input model.CreateUserInput) (*model.User, error) {
	log.Printf("[Gateway] CreateUser: name=%q, email=%q", input.Name, input.Email)
	resp, err := r.UserClient.CreateUser(ctx, &userpb.CreateUserRequest{
		Name:  input.Name,
		Email: input.Email,
	})
	if err != nil {
		log.Printf("[Gateway] CreateUser Error: %v", err)
		return nil, fmt.Errorf("CreateUser gRPC error: %w", err)
	}
	log.Printf("[Gateway] CreateUser Success: ID=%s", resp.GetUser().GetId())
	return protoToUser(resp.GetUser()), nil
}

// UpdateUser is the resolver for the updateUser field.
func (r *mutationResolver) UpdateUser(ctx context.Context, id string, input model.UpdateUserInput) (*model.User, error) {
	log.Printf("[Gateway] UpdateUser: ID=%s", id)
	req := &userpb.UpdateUserRequest{Id: id}
	if input.Name != nil {
		req.Name = *input.Name
	}
	if input.Email != nil {
		req.Email = *input.Email
	}
	resp, err := r.UserClient.UpdateUser(ctx, req)
	if err != nil {
		log.Printf("[Gateway] UpdateUser Error: %v", err)
		return nil, fmt.Errorf("UpdateUser gRPC error: %w", err)
	}
	log.Printf("[Gateway] UpdateUser Success: ID=%s", resp.GetUser().GetId())
	return protoToUser(resp.GetUser()), nil
}

// DeleteUser is the resolver for the deleteUser field.
func (r *mutationResolver) DeleteUser(ctx context.Context, id string) (string, error) {
	log.Printf("[Gateway] DeleteUser: ID=%s", id)
	resp, err := r.UserClient.DeleteUser(ctx, &userpb.DeleteUserRequest{Id: id})
	if err != nil {
		log.Printf("[Gateway] DeleteUser Error: %v", err)
		return "", fmt.Errorf("DeleteUser gRPC error: %w", err)
	}
	log.Printf("[Gateway] DeleteUser Success: %s", resp.GetMessage())
	return resp.GetMessage(), nil
}

// CreateOrder is the resolver for the createOrder field.
func (r *mutationResolver) CreateOrder(ctx context.Context, input model.CreateOrderInput) (*model.Order, error) {
	log.Printf("[Gateway] CreateOrder: userID=%s, product=%q, qty=%d", input.UserID, input.ProductName, input.Quantity)
	resp, err := r.OrderClient.CreateOrder(ctx, &orderpb.CreateOrderRequest{
		UserId:      input.UserID,
		ProductName: input.ProductName,
		Quantity:    int32(input.Quantity),
	})
	if err != nil {
		log.Printf("[Gateway] CreateOrder Error: %v", err)
		return nil, fmt.Errorf("CreateOrder gRPC error: %w", err)
	}
	log.Printf("[Gateway] CreateOrder Success: ID=%s", resp.GetOrder().GetId())
	return protoToOrder(resp.GetOrder()), nil
}

// UpdateOrder is the resolver for the updateOrder field.
func (r *mutationResolver) UpdateOrder(ctx context.Context, id string, input model.UpdateOrderInput) (*model.Order, error) {
	log.Printf("[Gateway] UpdateOrder: ID=%s", id)
	req := &orderpb.UpdateOrderRequest{Id: id}
	if input.ProductName != nil {
		req.ProductName = *input.ProductName
	}
	if input.Quantity != nil {
		req.Quantity = int32(*input.Quantity)
	}
	if input.Status != nil {
		req.Status = *input.Status
	}
	resp, err := r.OrderClient.UpdateOrder(ctx, req)
	if err != nil {
		log.Printf("[Gateway] UpdateOrder Error: %v", err)
		return nil, fmt.Errorf("UpdateOrder gRPC error: %w", err)
	}
	log.Printf("[Gateway] UpdateOrder Success: ID=%s", resp.GetOrder().GetId())
	return protoToOrder(resp.GetOrder()), nil
}

// DeleteOrder is the resolver for the deleteOrder field.
func (r *mutationResolver) DeleteOrder(ctx context.Context, id string) (string, error) {
	log.Printf("[Gateway] DeleteOrder: ID=%s", id)
	resp, err := r.OrderClient.DeleteOrder(ctx, &orderpb.DeleteOrderRequest{Id: id})
	if err != nil {
		log.Printf("[Gateway] DeleteOrder Error: %v", err)
		return "", fmt.Errorf("DeleteOrder gRPC error: %w", err)
	}
	log.Printf("[Gateway] DeleteOrder Success: %s", resp.GetMessage())
	return resp.GetMessage(), nil
}

// UpdateTracking is the resolver for the updateTracking field.
func (r *mutationResolver) UpdateTracking(ctx context.Context, input model.UpdateTrackingInput) (*model.OrderTracking, error) {
	log.Printf("[Gateway] UpdateTracking: orderID=%s, status=%q, location=%q", input.OrderID, input.Status, input.Location)
	resp, err := r.TrackingClient.UpdateTracking(ctx, &trackingpb.UpdateTrackingRequest{
		OrderId:  input.OrderID,
		Status:   input.Status,
		Location: input.Location,
	})
	if err != nil {
		log.Printf("[Gateway] UpdateTracking Error: %v", err)
		return nil, fmt.Errorf("UpdateTracking gRPC error: %w", err)
	}
	log.Printf("[Gateway] UpdateTracking Success: ID=%s", resp.GetTracking().GetId())
	return protoToTracking(resp.GetTracking()), nil
}

// GetUser is the resolver for the getUser field.
func (r *queryResolver) GetUser(ctx context.Context, id string) (*model.User, error) {
	log.Printf("[Gateway] GetUser: ID=%s", id)
	resp, err := r.UserClient.GetUser(ctx, &userpb.GetUserRequest{Id: id})
	if err != nil {
		log.Printf("[Gateway] GetUser Error: %v", err)
		return nil, fmt.Errorf("GetUser gRPC error: %w", err)
	}
	log.Printf("[Gateway] GetUser Success: ID=%s, name=%q", resp.GetUser().GetId(), resp.GetUser().GetName())
	return protoToUser(resp.GetUser()), nil
}

// ListUsers is the resolver for the listUsers field.
func (r *queryResolver) ListUsers(ctx context.Context) ([]*model.User, error) {
	log.Println("[Gateway] ListUsers")
	resp, err := r.UserClient.ListUsers(ctx, &userpb.ListUsersRequest{})
	if err != nil {
		log.Printf("[Gateway] ListUsers Error: %v", err)
		return nil, fmt.Errorf("ListUsers gRPC error: %w", err)
	}
	var users []*model.User
	for _, u := range resp.GetUsers() {
		users = append(users, protoToUser(u))
	}
	log.Printf("[Gateway] ListUsers Success: returned %d users", len(users))
	return users, nil
}

// GetOrder is the resolver for the getOrder field.
func (r *queryResolver) GetOrder(ctx context.Context, id string) (*model.Order, error) {
	log.Printf("[Gateway] GetOrder: ID=%s", id)
	resp, err := r.OrderClient.GetOrder(ctx, &orderpb.GetOrderRequest{Id: id})
	if err != nil {
		log.Printf("[Gateway] GetOrder Error: %v", err)
		return nil, fmt.Errorf("GetOrder gRPC error: %w", err)
	}
	log.Printf("[Gateway] GetOrder Success: ID=%s, product=%q", resp.GetOrder().GetId(), resp.GetOrder().GetProductName())
	return protoToOrder(resp.GetOrder()), nil
}

// ListOrders is the resolver for the listOrders field.
func (r *queryResolver) ListOrders(ctx context.Context) ([]*model.Order, error) {
	log.Println("[Gateway] ListOrders")
	resp, err := r.OrderClient.ListOrders(ctx, &orderpb.ListOrdersRequest{})
	if err != nil {
		log.Printf("[Gateway] ListOrders Error: %v", err)
		return nil, fmt.Errorf("ListOrders gRPC error: %w", err)
	}
	var orders []*model.Order
	for _, o := range resp.GetOrders() {
		orders = append(orders, protoToOrder(o))
	}
	log.Printf("[Gateway] ListOrders Success: returned %d orders", len(orders))
	return orders, nil
}

// TrackOrder is the resolver for the trackOrder field.
func (r *queryResolver) TrackOrder(ctx context.Context, orderID string) ([]*model.OrderTracking, error) {
	log.Printf("[Gateway] TrackOrder: orderID=%s", orderID)
	resp, err := r.TrackingClient.TrackOrder(ctx, &trackingpb.TrackOrderRequest{OrderId: orderID})
	if err != nil {
		log.Printf("[Gateway] TrackOrder Error: %v", err)
		return nil, fmt.Errorf("TrackOrder gRPC error: %w", err)
	}
	var trackings []*model.OrderTracking
	for _, t := range resp.GetTrackings() {
		trackings = append(trackings, protoToTracking(t))
	}
	log.Printf("[Gateway] TrackOrder Success: returned %d tracking events", len(trackings))
	return trackings, nil
}

// Mutation returns graph.MutationResolver implementation.
func (r *Resolver) Mutation() graph.MutationResolver { return &mutationResolver{r} }

// Query returns graph.QueryResolver implementation.
func (r *Resolver) Query() graph.QueryResolver { return &queryResolver{r} }

type mutationResolver struct{ *Resolver }
type queryResolver struct{ *Resolver }
