name: Docker CI/CD

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Build API Gateway
        run: docker build -t api-gateway -f api_gateway/Dockerfile api_gateway
      - name: Build User Service
        run: docker build -t user-service -f services/user_service/Dockerfile services/user_service
      - name: Build Order Service
        run: docker build -t order-service -f services/order_service/Dockerfile services/order_service
      - name: Build Tracking Service
        run: docker build -t tracking-service -f services/tracking_service/Dockerfile services/tracking_service

  push:
    runs-on: ubuntu-latest
    if: github.event_name == 'push'
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and Push API Gateway
        uses: docker/build-push-action@v6
        with:
          context: ./api_gateway
          file: ./api_gateway/Dockerfile
          push: true
          tags: shreyasbhat135/api-gateway:latest
